version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "climatepolicyradar/deng"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "climatepolicyradar/deng"
