version: 2
updates:
  - package-ecosystem: pip
    commit-message:
      prefix: feat
      include: scope
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - climatepolicyradar/deng
  - package-ecosystem: github-actions
    commit-message:
      prefix: feat
      include: scope
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - climatepolicyradar/deng
