name: code-quality
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      # For trunk to post annotations
      checks: write
      # For repo checkout
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.create false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --ci

      - name: Check code contains no FIXME's
        run: |
          git grep -r --no-color ${case_sensitive} --line-number -e "FIXME" :^.github
          if [[ $? -eq 0 ]]; then
            # if we found any FIXME entries in checked in files, fail on main
            exit 1
          else
            exit 0
          fi
        shell: bash {0}
